MODEL:
  BACKBONE:
    FREEZE_AT: 0
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STEM_TYPE: "basic"  # not used
    STEM_OUT_CHANNELS: 64
    STRIDE_IN_1X1: False
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
  META_ARCHITECTURE: "DCNet"
  SEM_SEG_HEAD:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  DCNET:
    DEEP_SUPERVISION: True
    CLASS_WEIGHT: 1.0
    DICE_WEIGHT: 1.0
    MASK_WEIGHT: 20.0
    NUM_OBJECT_QUERIES: 10
    DEC_LAYERS: 6
DATASETS:
  TRAIN: ("cod10k_train",)
  TEST: ("cod10k_test", "nc4k_test")
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 0.0001
  STEPS: (70000, 90000)
  MAX_ITER: 100000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05
  OPTIMIZER: "ADAMW"
  BACKBONE_MULTIPLIER: 0.1
  AMP:
    ENABLED: True
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
  DETECTIONS_PER_IMAGE: 10
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
OUTPUT_DIR: output